import React from 'react';
import SectionCard, { inputClass, labelClass } from './SectionCard';

// Internal fields reserved for Hermes Lab — not rendered on the public site.
const FIELDS = [
  { key: 'article_uuid', label: 'Article UUID' },
  { key: 'hermes_project_id', label: 'Hermes Project ID' },
  { key: 'ai_version', label: 'AI Version' },
  { key: 'generated_by', label: 'Generated By' },
  { key: 'generated_date', label: 'Generated Date' },
  { key: 'last_ai_review', label: 'Reviewed Date' },
  { key: 'last_ai_analysis', label: 'Last AI Analysis' },
  { key: 'last_optimised', label: 'Last Optimised' },
  { key: 'research_version', label: 'Research Version' },
  { key: 'seo_version', label: 'SEO Version' },
  { key: 'prompt_version', label: 'Prompt Version' },
  { key: 'language', label: 'Language' },
  { key: 'target_region', label: 'Target Region' },
  { key: 'ai_confidence', label: 'AI Confidence' },
  { key: 'hermes_confidence', label: 'Hermes Confidence' },
  { key: 'content_score', label: 'Content Score' },
  { key: 'quality_score', label: 'Quality Score' },
  { key: 'topic_cluster', label: 'Topic Cluster' },
  { key: 'primary_keyword', label: 'Primary Keyword' },
  { key: 'competitor_score', label: 'Competitor Score' },
  { key: 'content_freshness', label: 'Content Freshness' },
  { key: 'schema_version', label: 'Schema Version' },
];

export default function HermesMetadataSection({ data, update }) {
  const hm = data.hermes_metadata || {};
  const updateHermes = (field, value) => update('hermes_metadata', { ...hm, [field]: value });

  return (
    <SectionCard
      title="Hermes Metadata"
      description="Internal — populated by Hermes Lab. Not shown publicly."
      collapsible
      defaultOpen={false}
      accent="hermes"
    >
      <div className="rounded-lg bg-midnight/[0.03] border border-midnight/10 p-4">
        <p className="text-xs text-midnight/50">
          These fields are reserved for Hermes Lab. They will be populated automatically when Hermes integration is connected.
        </p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {FIELDS.map(({ key, label }) => (
          <div key={key}>
            <label className={labelClass}>{label}</label>
            <input type="text" value={hm[key] || ''} onChange={(e) => updateHermes(key, e.target.value)} className={inputClass} />
          </div>
        ))}
        <div className="md:col-span-2">
          <label className={labelClass}>Secondary Keywords</label>
          <input
            type="text"
            value={(hm.secondary_keywords || []).join(', ')}
            onChange={(e) => updateHermes('secondary_keywords', e.target.value.split(',').map((s) => s.trim()).filter(Boolean))}
            placeholder="comma, separated, keywords"
            className={inputClass}
          />
        </div>
      </div>
    </SectionCard>
  );
}